"""polarity table

Revision ID: 1fd237af10b0
Revises: 9df073579791
Create Date: 2018-08-25 16:54:07.145253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd237af10b0'
down_revision = '9df073579791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_polarity', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'current_polarity')
    # ### end Alembic commands ###
