"""new fields in user model

Revision ID: caa50377c806
Revises: f566677fa8ee
Create Date: 2018-08-21 21:45:28.234081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caa50377c806'
down_revision = 'f566677fa8ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_mode', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'current_mode')
    # ### end Alembic commands ###
